import {TokenInterface} from "./TokenInterface";

export interface ChartItemInterface {
    active: boolean,
    antiWhale: any | null,
    aprDaily: number,
    aprWeekly: number,
    aprYearly: number,
    apyYearly: number,
    asset: string,
    assetAddress: any | null,
    assetId: string,
    assetLockup: boolean,
    assetPopupMessage: any | null,
    assetPrice: number,
    auditInfo: any | null,
    blockchain: string,
    category: any | null,
    collateralLockPeriod: any | null,
    d_active_reason: any | null,
    dateAdded: string,
    dateEnding: any | null,
    dateStarted: any | null,
    dateUpdated: string,
    daysRemaining: any | null,
    depositFee: any | null,
    exchangeName: any | null,
    exchangePicture: any | null,
    exchangeUrl: any | null,
    exchangeVersion: any | null,
    farm: string,
    farmId: string,
    farmImage: any | null,
    farmName: string,
    farmType: any | null,
    feeAprYearly: number,
    harvestLockup: any | null,
    harvestLockupInfo: any | null,
    impermanentLoss: any | null,
    impermanentLoss30d: any | null,
    info: any | null,
    investmentLink: any | null,
    manuallyCalculatedAPR: boolean,
    maxPoolCap: any | null,
    multiplier: any | null,
    nativeToken: any | null,
    nativeTokenAddress: any | null,
    nativeTokenInvestLink: any | null,
    nativeTokenMarketCap: number,
    nativeTokenPrice: number,
    new_asset: boolean,
    otherFees: any | null,
    otherPoolEconomicsInfo: any | null,
    pid: number,
    poolAlreadyFilled: boolean,
    priceCorrelation_3numberd: any | null,
    rewardTokenA: any | null,
    rewardTokenAAddress: any | null,
    rewardTokenAAprYearly: number,
    rewardTokenAAprYearlyMaxBoosted: number,
    rewardTokenAPrice: number,
    rewardTokenAWeeklyAmount: number,
    rewardTokenAWeeklyDollarAmount: number,
    rewardTokenB: any | null,
    rewardTokenBAddress: any | null,
    rewardTokenBAprYearly: number,
    rewardTokenBAprYearlyMaxBoosted: number,
    rewardTokenBPrice: number,
    rewardTokenBWeeklyAmount: number,
    rewardTokenBWeeklyDollarAmount: number,
    scam: boolean,
    scamInfo: any | null,
    selected_farm: [
        {
            active: boolean,
            blockchain: string,
            dateAdded: string,
            dateUpdated:string,
            farmId: string,
            farmName: string,
            farmType:string,
            lastFullUpdate: string,
            scam: boolean,
            scamInfo:string,
            tvlChange24h:string,
            tvlChange24hValue: number,
            tvlStaked: number,
            tvlStakedHistory: TokenInterface[]
        }
    ],
    stakingAddress: any | null,
    stakingLink: string,
    status: string,
    tokenA: any | null,
    tokenAAddress: any | null,
    tokenABacking: number,
    tokenAHolders: number,
    tokenAHoldersHistory: TokenInterface[]
    ,
    tokenAPicture: any | null,
    tokenAPrice: number,
    tokenAPriceHistory: TokenInterface[],
    tokenB: any | null,
    tokenBAddress: any | null,
    tokenBBacking: number,
    tokenBHolders: number,
    tokenBPicture: any | null,
    tokenBPrice: number,
    tokenC: any | null,
    tokenCAddress: any | null,
    tokenCBacking: number,
    tokenCHolders: number,
    tokenCPicture: any | null,
    tokenCPrice: number,
    tokenD: any | null,
    tokenDAddress: any | null,
    tokenDBacking: number,
    tokenDHolders: number,
    tokenDPicture: any | null,
    tokenDPrice: number,
    tokenE: any | null,
    tokenEAddress: any | null,
    tokenEBacking: number,
    tokenEHolders: number,
    tokenEPicture: any | null,
    tokenEPrice: number,
    transferTax: any | null,
    transferTaxInfo: any | null,
    tvlChange24h: string,
    tvlChange24hValue: number,
    tvlExchange: number,
    tvlFarm: number,
    tvlStaked: number,
    underlyingFarm: any | null,
    url: any | null,
    vaultAddress: any | null,
    volume_24h: any | null,
    weight: any | null,
    withdrawalFee: any | null,
    yearlyTokenRewardPool: number,
    yieldType: string
}
